# Generated by Django 4.1.6 on 2023-02-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_title_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
