# Generated by Django 4.1.6 on 2023-02-19 05:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0003_title_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='fav_book', to=settings.AUTH_USER_MODEL),
        ),
    ]
