# Generated by Django 4.1.6 on 2023-02-19 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_title_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='favorite',
        ),
    ]
