# Generated by Django 4.1.6 on 2023-02-20 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='date_collected',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='what_collect',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='who_collect',
        ),
    ]
