# Generated by Django 4.1.6 on 2023-02-20 05:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0007_remove_collection_date_collected_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.AddField(
            model_name='title',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='add_favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
