# Generated by Django 4.1.6 on 2023-02-21 03:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0008_delete_collection_title_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
